=== sreenithibalasu/UA_Metadata/united_airlines_reservation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://575airlineReservations.org/v1/"
    xmlns="http://575airlineReservation.org/v1/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
    
    <xs:import foaf:namespace="http://xmlns.com/foaf/0.1/" foaf:schemaLocation="index.rdf"/>   
    <xs:element name="airline_reservation_metadata">

        <xs:annotation>
            <xs:documentation>
                Categories: Passenger Name, Reservation ID, Flight Number, 
                Departure and Arrival Information, Layover Information, Trip Type (one-way or round-trip),
                Rewards/Loyalty Information, Trip Information, Lounge Information,
                Delays and Cancelations, Upgrade Information
            </xs:documentation>
        </xs:annotation>
        
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="Passenger_Name" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Reservation_ID" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Flight_Number" minOccurs="1" maxOccurs="unbounded"/>
              
                
                <xs:element name="Departure_Information" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Departure_Airport_Name" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
                            <xs:element name="Departure_Airport_Code" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
                            <xs:element name="Departure_DateTime" minOccurs="1" maxOccurs="unbounded" type="xs:dateTime"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Arrival_Information" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Arrival_Airport_Name" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
                            <xs:element name="Arrival_Airport_Code" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
                            <xs:element name="Arrival_DateTime" minOccurs="1" maxOccurs="unbounded" type="xs:dateTime"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Layover_Information" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Layover_Airport" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="Layover_Airport_Code" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="Layover_Time" minOccurs="0" maxOccurs="unbounded" type="xs:time"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                
                <xs:element name="Flight_Duration" minOccurs="1" maxOccurs="unbounded" type="xs:double"/>
                
                <xs:element name="Trip_Type" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="Chosen_Trip_Type">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="One-Way"/>
                                    <xs:enumeration value="Round Trip"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Booked_Class" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="Chosen_Class">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Economy"/>
                                    <xs:enumeration value="Premium Economy"/>
                                    <xs:enumeration value="Business"/>
                                    <xs:enumeration value="First"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Rewards_Information" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Rewards_Program" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="Chosen_Rewards_Program">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="United MileagePlus"/>
                                                <xs:enumeration value="Hilton Rewards Club"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element name="Rewards_Program_ID" maxOccurs="1" minOccurs="0" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                
                <xs:element name="Trip_Information">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Number_of_Checked_Bags" minOccurs="0" maxOccurs="1" type="xs:integer"/>
                            <xs:element name="Trip_Cost" maxOccurs="1" minOccurs="1" type="xs:double"/>
                            <xs:element name="Trip_Currency" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="Currency">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="USD"/>
                                                <xs:enumeration value="EUR"/>
                                                <xs:enumeration value="GBP"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Meal_Type" minOccurs="0" maxOccurs="3">
                    <xs:complexType>
                        <xs:attribute name="meals">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Steak"/>
                                    <xs:enumeration value="Fish"/>
                                    <xs:enumeration value="Tofu"/>
                                    <xs:enumeration value="Curry"/>
                                    <xs:enumeration value="Hamburger"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Delays" minOccurs="1" maxOccurs="1" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Flight_Delay" minOccurs="1" maxOccurs="1" type="xs:boolean"/>
                            <xs:element name="Reason_For_Delay" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Cancelations" minOccurs="1" maxOccurs="1" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Flight_Cancelation" minOccurs="0" maxOccurs="1" type="xs:boolean"/>
                            <xs:element name="Reason_For-Cancelation" minOccurs="0" maxOccurs="1"/>
                         
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Lounge_Information" minOccurs="1" maxOccurs="1" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Lounge_Access" minOccurs="1" maxOccurs="1" type="xs:boolean"/>
                            <xs:element name="Lounge_Access_Fee" minOccurs="0" maxOccurs="1" type="xs:double"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Upgrades_Information" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Upgrade_Waitlist_Position" minOccurs="0" maxOccurs="unbounded" type="xs:integer"/>
                            
                            <xs:element name="Seat_Upgrade" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="Original_Seat_Number">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string"/>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="Upgraded_Seat_Number">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string"/>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="Upgraded_Class">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string"></xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
               
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sreenithibalasu/UA_Metadata/Sample_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<airline_reservation_metadata xmlns="http://575airlineReservations.org/v1/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://575airlineReservations.org/v1/ file:/Users/sreenithibalasubramanian/Downloads/united_airlines_reservation.xsd">
    <Passenger_Name>Cherry O'Houlihan</Passenger_Name>
    <Reservation_ID>Z7C2BD</Reservation_ID>
    <Flight_Number>M2 4583</Flight_Number>
    <Departure_Information>
        <Departure_Airport_Name>San Francisco Int'l Airport</Departure_Airport_Name>
        <Departure_Airport_Code>SFO</Departure_Airport_Code>
        <Departure_DateTime>2023-04-11T10:00:00</Departure_DateTime>
    </Departure_Information>
    <Arrival_Information>
        <Arrival_Airport_Name>Cozumel Int'l Airport</Arrival_Airport_Name>
        <Arrival_Airport_Code>CZM</Arrival_Airport_Code>
        <Arrival_DateTime>2023-04-12T19:00:00</Arrival_DateTime>
    </Arrival_Information>
    <Layover_Information>
        <Layover_Airport>Dallas/Fort Worth Int'l Airport</Layover_Airport>
        <Layover_Airport_Code>DFW</Layover_Airport_Code>
        <Layover_Time>13:30:00</Layover_Time>
    </Layover_Information>
    <Flight_Duration>9</Flight_Duration>
    <Trip_Type Chosen_Trip_Type="Round Trip"/>
    <Booked_Class Chosen_Class="First"/>
    <Rewards_Information>
        <Rewards_Program Chosen_Rewards_Program="Hilton Rewards Club"/>
        <Rewards_Program_ID>UA-XXX367</Rewards_Program_ID>
    </Rewards_Information>
    <Trip_Information>
        <Number_of_Checked_Bags>5</Number_of_Checked_Bags>
        <Trip_Cost>465</Trip_Cost>
        <Trip_Currency Currency="USD"/>
    </Trip_Information>
    <Delays>
        <Flight_Delay>true</Flight_Delay>
        <Reason_For_Delay>Weather</Reason_For_Delay>
    </Delays>
    <Cancelations>
        <Flight_Cancelation>true</Flight_Cancelation>
        <Reason_For-Cancelation>Weather</Reason_For-Cancelation>
    </Cancelations>
    <Lounge_Information>
        <Lounge_Access>false</Lounge_Access>
    </Lounge_Information>
</airline_reservation_metadata>

=== sreenithibalasu/UA_Metadata/Sample_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<airline_reservation_metadata xmlns="http://575airlineReservations.org/v1/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://575airlineReservations.org/v1/ file:/Users/sreenithibalasubramanian/Downloads/united_airlines_reservation.xsd">
    <Passenger_Name>Sreenithi Balasubramanian</Passenger_Name>
    <Reservation_ID>AB1212</Reservation_ID>
    <Flight_Number>UA345</Flight_Number>
    <Departure_Information>
        <Departure_Airport_Name>San Francisco International Airport</Departure_Airport_Name>
        <Departure_Airport_Code>SFO</Departure_Airport_Code>
        <Departure_DateTime>2022-12-09T09:00:00</Departure_DateTime>
    </Departure_Information>
    <Arrival_Information>
        <Arrival_Airport_Name>Seattle-Tacoma International Airport</Arrival_Airport_Name>
        <Arrival_Airport_Code>SEA</Arrival_Airport_Code>
        <Arrival_DateTime>2022-12-09T11:30:00</Arrival_DateTime>
    </Arrival_Information>
    <Layover_Information>
        <Layover_Airport>Portland International Airport</Layover_Airport>
        <Layover_Airport_Code>PDX</Layover_Airport_Code>
        <Layover_Time>01:00:00</Layover_Time>
    </Layover_Information>
    <Flight_Duration>3.5</Flight_Duration>
    <Trip_Type Chosen_Trip_Type="One-Way"/>
    <Booked_Class Chosen_Class="Business"/>
    <Rewards_Information>
        <Rewards_Program Chosen_Rewards_Program="Hilton Rewards Club"/>
        <Rewards_Program_ID>HIL98873689041</Rewards_Program_ID>
    </Rewards_Information>
    <Trip_Information>
        <Number_of_Checked_Bags>0</Number_of_Checked_Bags>
        <Trip_Cost>450</Trip_Cost>
        <Trip_Currency Currency="USD"/>
    </Trip_Information>
    <Meal_Type meals="Tofu"/>
    <Delays>
        <Flight_Delay>0</Flight_Delay>
    </Delays>
    <Cancelations>
        <Flight_Cancelation>0</Flight_Cancelation>
    </Cancelations>
    <Lounge_Information>
        <Lounge_Access>1</Lounge_Access>
        <Lounge_Access_Fee>50</Lounge_Access_Fee>
    </Lounge_Information>
    <Upgrades_Information>
        <Upgrade_Waitlist_Position>1</Upgrade_Waitlist_Position>
        <Seat_Upgrade Original_Seat_Number="11A" Upgraded_Seat_Number="1A" Upgraded_Class="First"/>
    </Upgrades_Information>
</airline_reservation_metadata>

=== sreenithibalasu/UA_Metadata/Sample_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<airline_reservation_metadata xmlns="http://575airlineReservations.org/v1/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://575airlineReservations.org/v1/ file:/Users/sreenithibalasubramanian/Downloads/united_airlines_reservation.xsd">
    <Passenger_Name>Sreenithi Balasubramanian</Passenger_Name>
    <Reservation_ID>D1P9P9</Reservation_ID>
    <Flight_Number>UA255</Flight_Number>
    <Departure_Information>
        <Departure_Airport_Name>Chicago O'Hare International Airport</Departure_Airport_Name>
        <Departure_Airport_Code>ORD</Departure_Airport_Code>
        <Departure_DateTime>2022-12-09T14:22:00</Departure_DateTime>
    </Departure_Information>
    <Arrival_Information>
        <Arrival_Airport_Name>Los Angeles International Airport</Arrival_Airport_Name>
        <Arrival_Airport_Code>LAX</Arrival_Airport_Code>
        <Arrival_DateTime>2022-12-09T16:55:00</Arrival_DateTime>
    </Arrival_Information>
    <Flight_Duration>4.5</Flight_Duration>
    <Trip_Type Chosen_Trip_Type="Round Trip"/>
    <Booked_Class Chosen_Class="Premium Economy"/>
    <Rewards_Information>
        <Rewards_Program Chosen_Rewards_Program="United MileagePlus"/>
        <Rewards_Program_ID>UA117777175</Rewards_Program_ID>
    </Rewards_Information>
    <Trip_Information>
        <Number_of_Checked_Bags>1</Number_of_Checked_Bags>
        <Trip_Cost>182</Trip_Cost>
        <Trip_Currency Currency="USD"/>
    </Trip_Information>
    <Delays>
        <Flight_Delay>0</Flight_Delay>
    </Delays>
    <Cancelations>
        <Flight_Cancelation>0</Flight_Cancelation>
    </Cancelations>
    <Lounge_Information>
        <Lounge_Access>1</Lounge_Access>
    </Lounge_Information>
</airline_reservation_metadata>

=== sreenithibalasu/UA_Metadata/Sample_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<airline_reservation_metadata xmlns="http://575airlineReservations.org/v1/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://575airlineReservations.org/v1/ file:/Users/sreenithibalasubramanian/Downloads/united_airlines_reservation.xsd">
    <Passenger_Name>Ben Ackley</Passenger_Name>
    <Reservation_ID>I8D3GF</Reservation_ID>
    <Flight_Number>F9 1025</Flight_Number>
    <Departure_Information>
        <Departure_Airport_Name>Chicago Midway Airport</Departure_Airport_Name>
        <Departure_Airport_Code>MDW</Departure_Airport_Code>
        <Departure_DateTime>2022-12-13T20:50:00</Departure_DateTime>
    </Departure_Information>
    <Arrival_Information>
        <Arrival_Airport_Name>Orlando Int'l Airport</Arrival_Airport_Name>
        <Arrival_Airport_Code>ORL</Arrival_Airport_Code>
        <Arrival_DateTime>2022-12-13T23:26:00</Arrival_DateTime>
    </Arrival_Information>
    <Flight_Duration>2.6</Flight_Duration>
    <Trip_Type Chosen_Trip_Type="Round Trip"/>
    <Booked_Class Chosen_Class="Economy"/>
    <Trip_Information>
        <Number_of_Checked_Bags>1</Number_of_Checked_Bags>
        <Trip_Cost>138</Trip_Cost>
        <Trip_Currency Currency="USD"/>
    </Trip_Information>
    <Delays>
        <Flight_Delay>false</Flight_Delay>
    </Delays>
    <Cancelations>
        <Flight_Cancelation>false</Flight_Cancelation>
    </Cancelations>
    <Lounge_Information>
        <Lounge_Access>false</Lounge_Access>
    </Lounge_Information>
</airline_reservation_metadata>
